"""Add more iGEM BioBrick parts to the database."""

import sys
sys.path.insert(0, ".")

from app.database import SessionLocal, engine, Base
from app.models.parts import Part

# Additional iGEM BioBrick parts
ADDITIONAL_PARTS = [
    # More Anderson Promoters
    {
        "name": "BBa_J23103",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.01 (very weak)",
        "sequence": "CTGATAGCTAGCTCAGTCCTAGGGATTATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23104",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.72",
        "sequence": "TTGACAGCTAGCTCAGTCCTAGGTATTGTGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23105",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.24",
        "sequence": "TTTACGGCTAGCTCAGTCCTAGGTACTATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23107",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.36",
        "sequence": "TTTACGGCTAGCTCAGCCCTAGGTATTATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23108",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.51",
        "sequence": "CTGACAGCTAGCTCAGTCCTAGGTATAATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23109",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.04 (weak)",
        "sequence": "TTTACAGCTAGCTCAGTCCTAGGGACTGTGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23110",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.33",
        "sequence": "TTTACGGCTAGCTCAGTCCTAGGTACAATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23111",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.58",
        "sequence": "TTGACGGCTAGCTCAGTCCTAGGTATAGTGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23112",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.00 (inactive)",
        "sequence": "CTGACAGCTAGCTCAGTCCTAGGGATTATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23113",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.01 (very weak)",
        "sequence": "CTGATGGCTAGCTCAGTCCTAGGGATTATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23114",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.10",
        "sequence": "TTTATGGCTAGCTCAGTCCTAGGTACAATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23115",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.15",
        "sequence": "TTTATAGCTAGCTCAGCCCTTGGTACAATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23116",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.16",
        "sequence": "TTGACAGCTAGCTCAGTCCTAGGGACTATGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23117",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.06",
        "sequence": "TTGACAGCTAGCTCAGTCCTAGGGATTGTGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J23118",
        "type": "promoter",
        "description": "Constitutive promoter from Anderson collection. Relative strength: 0.56",
        "sequence": "TTGACGGCTAGCTCAGTCCTAGGTATTGTGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # T7 and other promoters
    {
        "name": "BBa_I712074",
        "type": "promoter",
        "description": "T7 promoter. Very strong promoter for T7 RNA polymerase.",
        "sequence": "TAATACGACTCACTATAGGG",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_R0011",
        "type": "promoter",
        "description": "LacI-regulated, lambda pL hybrid promoter. Stronger than R0010.",
        "sequence": "AATTGTGAGCGGATAACAATTTCACACAGGAAACAGCTATGACCATG",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_I0500",
        "type": "promoter",
        "description": "Inducible pBad/araC promoter. Arabinose-inducible.",
        "sequence": "ACTTTTCATACTCCCGCCATTCAGAGAAGAAACCAATTGTCCATATTGCATCAGACATTGCCGTCACTGCGTCTTTTACTGGCTCTTCTCGCTAACCAAACCGGTAACCCCGCTTATTAAAAGCATTCTGTAACAAAGCGGGACCAAAGCCATGACAAAAACGCGTAACAAAAGTGTCTATAATCACGGCAGAAAAGTCCACATTGATTATTTGCACGGCGTCACACTTTGCTATGCCATAGCATTTTTATCCATAAGATTAGCGGATCCTACCTGACGCTTTTTATCGCAACTCTCTACTGTTTCTCCATACCCGTTTTTTTGGGCTAGC",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # More RBS
    {
        "name": "BBa_B0033",
        "type": "rbs",
        "description": "Weak RBS. Based on B0030, weaker translation initiation.",
        "sequence": "TCTAGAGTTAAAGAGGAGAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_B0035",
        "type": "rbs",
        "description": "Medium-weak RBS. Fine-tuned translation efficiency.",
        "sequence": "TCTAGAGATTAAAGAGGAGAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J61100",
        "type": "rbs",
        "description": "Community collection RBS. Strength ~1 MEAU.",
        "sequence": "AAAGAGGAGAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J61101",
        "type": "rbs",
        "description": "Community collection RBS. Strength ~3.5 MEAU.",
        "sequence": "AAAGAGGGGAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J61104",
        "type": "rbs",
        "description": "Community collection RBS. Strength ~100 MEAU.",
        "sequence": "AAAGAAGGAGAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_J61107",
        "type": "rbs",
        "description": "Community collection RBS. Strength ~500 MEAU.",
        "sequence": "AAAGACAGGAGAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # More terminators
    {
        "name": "BBa_B0011",
        "type": "terminator",
        "description": "LuxICDABEG (and target LuxR) terminator from V. fischeri.",
        "sequence": "GGAAACACAGAAAAAAGCCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGG",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_B0014",
        "type": "terminator",
        "description": "Terminator upstream of luxR. Forward terminator.",
        "sequence": "TCACACTGGCTCACCTTCGGGTGGGCCTTTCTGCGTTTATATACTAGAGACCTGTAGGATCGTACAGGTTTACGCAAGAAAATGGTTTGTTATAGTCGAATAAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_B1001",
        "type": "terminator",
        "description": "Bi-directional terminator. Terminates transcription in both directions.",
        "sequence": "GGAAACACAGAAAAAAGCCCGCACCTGACAGTGCGGGCTTTTTTTTCGACCAAAGGTCGCCCGACGCCCGGGCTTTTTTTTTCGACCAAAGG",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_B1002",
        "type": "terminator",
        "description": "Another bi-directional terminator variant.",
        "sequence": "CGCAAAAAACCCCGCTTCGGCGGGGTTTTTTCGCGGAAACACAGAAAAAAGCCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGG",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # Reporter genes - Fluorescent proteins
    {
        "name": "BBa_E0020",
        "type": "gene",
        "description": "eCFP cyan fluorescent protein. Excitation 434nm, Emission 477nm.",
        "sequence": "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTGGGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACATCAGCCACAACGTCTATATCACCGCCGACAAGCAGAAGAACGGCATCAAGGCCAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_E0030",
        "type": "gene",
        "description": "eYFP yellow fluorescent protein. Excitation 514nm, Emission 527nm.",
        "sequence": "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCTTCGGCTACGGCCTGCAGTGCTTCGCCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCTACCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_K1033916",
        "type": "gene",
        "description": "mCherry red fluorescent protein. Improved mRFP variant. Excitation 587nm, Emission 610nm.",
        "sequence": "ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTGCACATGGAGGGCTCCGTGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCACCCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCGAGTTCATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAGGCCTCCTCCGAGCGGATGTACCCCGAGGACGGCGCCCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGACGGCGGCCACTACGACGCTGAGGTCAAGACCACCTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAACATCAAGTTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_K515105",
        "type": "gene",
        "description": "Venus yellow fluorescent protein. Fast-maturing YFP variant.",
        "sequence": "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGGGCTACGGCCTGCAGTGCTTCGCCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCTACCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # Luciferase reporters
    {
        "name": "BBa_K325909",
        "type": "gene",
        "description": "Firefly luciferase. Bioluminescent reporter, emits light at 562nm.",
        "sequence": "ATGGAAGACGCCAAAAACATAAAGAAAGGCCCGGCGCCATTCTATCCGCTGGAAGATGGAACCGCTGGAGAGCAACTGCATAAGGCTATGAAGAGATACGCCCTGGTTCCTGGAACAATTGCTTTTACAGATGCACATATCGAGGTGGACATCACTTACGCTGAGTACTTCGAAATGTCCGTTCGGTTGGCAGAAGCTATGAAACGATATGGGCTGAATACAAATCACAGAATCGTCGTATGCAGTGAAAACTCTCTTCAATTCTTTATGCCGGTGTTGGGCGCGTTATTTATCGGAGTTGCAGTTGCGCCCGCGAACGACATTTATAATGAACGTGAATTGCTCAACAGTATGGGCATTTCGCAGCCTACCGTGGTGTTCGTTTCCAAAAAGGGGTTGCAAAAAATTTTGAACGTGCAAAAAAAGCTCCCAATCATCCAAAAAATTATTATCATGGATTCTAAAACGGATTACCAGGGATTTCAGTCGATGTACACGTTCGTCACATCTCATCTACCTCCCGGTTTTAATGAATACGATTTTGTGCCAGAGTCCTTCGATAGGGACAAGACAATTGCACTGATCATGAACTCCTCTGGATCTACTGGTCTGCCTAAAGGTGTCGCTCTGCCTCATAGAACTGCCTGCGTGAGATTCTCGCATGCCAGAGATCCTATTTTTGGCAATCAAATCATTCCGGATACTGCGATTTTAAGTGTTGTTCCATTCCATCACGGTTTTGGAATGTTTACTACACTCGGATATTTGATATGTGGATTTCGAGTCGTCTTAATGTATAGATTTGAAGAAGAGCTGTTTCTGAGGAGCCTTCAGGATTACAAGATTCAAAGTGCGCTGCTGGTGCCAACCCTATTCTCCTTCTTCGCCAAAAGCACTCTGATTGACAAATACGATTTATCTAATTTACACGAAATTGCTTCTGGTGGCGCTCCCCTCTCTAAGGAAGTCGGGGAAGCGGTTGCCAAGAGGTTCCATCTGCCAGGTATCAGGCAAGGATATGGGCTCACTGAGACTACATCAGCTATTCTGATTACACCCGAGGGGGATGATAAACCGGGCGCGGTCGGTAAAGTTGTTCCATTTTTTGAAGCGAAGGTTGTGGATCTGGATACCGGGAAAACGCTGGGCGTTAATCAAAGAGGCGAACTGTGTGTGAGAGGTCCTATGATTATGTCCGGTTATGTAAACAATCCGGAAGCGACCAACGCCTTGATTGACAAGGATGGATGGCTACATTCTGGAGACATAGCTTACTGGGACGAAGACGAACACTTCTTCATCGTTGACCGCCTGAAGTCTCTGATTAAGTACAAAGGCTATCAGGTGGCTCCCGCTGAATTGGAATCCATCTTGCTCCAACACCCCAACATCTTCGACGCAGGTGTCGCAGGTCTTCCCGACGATGACGCCGGTGAACTTCCCGCCGCCGTTGTTGTTTTGGAGCACGGAAAGACGATGACGGAAAAAGAGATCGTGGATTACGTCGCCAGTCAAGTAACAACCGCGAAAAAGTTGCGCGGAGGAGTTGTGTTTGTGGACGAAGTACCGAAAGGTCTTACCGGAAAACTCGACGCAAGAAAAATCAGAGAGATCCTCATAAAGGCCAAGAAGGGCGGAAAGATCGCCGTGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # Enzymes and useful proteins
    {
        "name": "BBa_K1189008",
        "type": "gene",
        "description": "SpCas9 - CRISPR-associated protein 9 from S. pyogenes. Used for genome editing.",
        "sequence": "ATGGATAAGAAATACTCAATAGGCTTAGATATCGGCACAAATAGCGTCGGATGGGCGGTGATCACTGATGATTATAAGGTTCCGTCTAAAAAGTTCAAGGTTCTGGGAAATACAGACCGCCACAGTATCAAAAAAAATCTTATAGGGGCTCTTTTATTTGGCAGTGGAGAGACAGCGGAAGCGACTCGTCTCAAACGGACAGCTCGTAGAAGGTATACACGTCGGAAGAATCGTATTTGTTATCTACAGGAGATTTTTTCAAATGAGATGGCGAAAGTAGATGATAGTTTCTTTCATCGACTTGAAGAGTCTTTTTTGGTGGAAGAAGACAAGAAGCATGAACGTCATCCTATTTTTGGAAATATAGTAGATGAAGTTGCTTATCATGAGAAATATCCAACTATCTATCATCTGCGAAAAAAATTGGCAGATTCTACTGATAAAGCGGATTTGCGCTTAATCTATTTGGCCTTAGCGCATATGATTAAGTTTCGTGGTCATTTTTTGATTGAGGGAGATTTAAATCCTGATAATAGTGATGTGGACAAACTATTTATCCAGTTGGTACAAATCTACAATCAATTATTTGAAGAAAACCCTATTAACGCAAGTGGAGTAGATGCTAAAGCGATTCTTTCTGCACGATTGAGTAAATCAAGACGATTAGAAAATCTCATTGCTCAGCTCCCCGGTGAGAAGAGAAATGGCTTGTTTGGGAATCTCATTGCTTTGTCATTGGGATTGACCCCTAATTTTAAATCAAATTTTGATTTGGCAGAAGATGCTAAATTACAGCTTTCAAAAGATACTTACGATGATGATTTAGATAATTTATTGGCGCAAATTGGAGATCAATATGCTGATTTGTTTTTGGCAGCTAAGAATTTATCAGATGCTATTTTACTTTCAGATATCCTAAGAGTAAATAGTGAAATAACTAAGGCTCCCCTATCAGCTTCAATGATTAAGCGCTACGATGAACATCATCAAGACTTGACTCTTTTAAAAGCTTTAGTTCGACAACAACTTCCAGAAAAGTATAAAGAAATCTTTTTTGATCAATCAAAAAACGGATATGCAGGTTATATTGATGGGGGAGCTAGCCAAGAAGAATTTTATAAATTTATCAAACCAATTTTAGAAAAAATGGATGGTACTGAGGAATTATTGGTGAAACTAAATCGTGAAGATTTGCTGCGCAAGCAACGGACCTTTGACAACGGCTCTATTCCCCATCAAATTCACTTGGGTGAGCTGCATGCTATTTTGAGAAGACAAGAAGACTTTTATCCATTTTTAAAAGACAATCGTGAGAAGATTGAAAAAATCTTGACTTTTCGAATTCCTTATTATGTTGGTCCATTGGCGCGTGGCAATAGTCGTTTTGCATGGATGACTCGGAAGTCTGAAGAAACAATTACCCCATGGAATTTTGAAGAAGTTGTCGATAAAGGTGCTTCAGCTCAATCATTTATTGAACGCATGACAAACTTTGATAAAAATCTTCCAAATGAAAAAGTACTACCAAAACATAGTTTGCTTTATGAGTATTTTACGGTTTATAACGAATTGACAAAGGTCAAATATGTTACTGAGGGAATGCGAAAACCAGCATTTCTTTCAGGTGAACAGAAGAAAGCCATTGTTGATTTACTCTTCAAAACAAATCGAAAAGTAACCGTTAAGCAATTAAAAGAAGATTATTTCAAAAAAATAGAATGTTTTGATAGTGTTGAAATTTCAGGAGTTGAAGATAGATTTAATGCTTCATTAGGCGCCTACCATGATTTGCTAAAAATTATTAAAGATAAAGATTTTTTGGATAATGAAGAAAATGAAGATATCTTAGAGGATATTGTTTTAACATTGACCTTATTTGAAGATAGGGGGATGATTGAGGAAAGACTTAAAACATATGCTCACCTCTTTGATGATAAGGTGATGAAACAGCTTAAACGTCGCCGTTATACTGGTTGGGGACGTTTGTCTCGAAAATTGATTAATGGTATTAGGGATAAGCAATCTGGCAAAACAATATTAGATTTTTTGAAATCAGATGGTTTTGCCAATCGCAATTTTATGCAGCTGATCCATGATGATAGTTTGACATTTAAAGAAGATATTCAAAAAGCACAGGTGTCTGGACAAGGCCATAGTTTACATGAACAGATTGCTAACTTAGCTGGCAGTCCTGCTATTAAAAAAGGTATTTTACAGACTGTAAAAATTGTTGATGAACTGGTCAAAGTAATGGGGCATAAGCCAGAAAATATCGTTATTGAAATGGCACGTGAAAATCAGACAACTCAAAAGGGCCAGAAAAATTCGCGAGAGCGTATGAAACGAATCGAAGAAGGTATCAAAGAATTAGGAAGTCAGATTCTTAAAGAGCATCCTGTTGAAAATACTCAATTGCAAAATGAAAAGCTCTATCTCTATTATCTACAAAATGGAAGAGACATGTATGTGGACCAAGAATTAGATATTAATCGTTTAAGTGATTATGATGTCGATCACATTGTTCCACAAAGTTTCATTAAAGACGATTCAATAGACAATAAGGTACTAACGCGTTCTGATAAAAATCGTGGTAAATCGGATAACGTTCCAAGTGAAGAAGTAGTCAAAAAGATGAAAAACTATTGGAGACAACTTCTAAACGCCAAGTTAATCACTCAACGTAAGTTTGATAATTTAACGAAAGCTGAACGTGGAGGTTTGAGTGAACTTGATAAAGCTGGTTTTATCAAACGCCAATTGGTTGAAACTCGCCAAATCACTAAGCATGTGGCACAAATTTTGGATAGTCGCATGAATACTAAATACGATGAAAATGATAAACTTATTCGAGAGGTTAAAGTGATTACCTTAAAATCTAAATTAGTTTCTGACTTCCGAAAAGATTTCCAATTCTATAAAGTACGTGAGATTAACAATTACCATCATGCCCATGATGCGTATCTAAATGCCGTCGTTGGAACTGCTTTGATTAAGAAATATCCAAAACTTGAATCGGAGTTTGTCTATGGTGATTATAAAGTTTATGATGTTCGTAAAATGATTGCTAAGTCTGAGCAAGAAATAGGCAAAGCAACCGCAAAATATTTCTTTTACTCTAATATCATGAACTTCTTCAAAACAGAAATTACACTTGCAAATGGAGAGATTCGCAAACGCCCTCTAATCGAAACTAATGGGGAAACTGGAGAAATTGTCTGGGATAAAGGGCGAGATTTTGCCACAGTGCGCAAAGTATTGTCCATGCCCCAAGTCAATATTGTCAAGAAAACAGAAGTACAGACAGGCGGATTCTCCAAGGAGTCAATTTTACCAAAAAGAAATTCGGACAAGCTTATTGCTCGTAAAAAAGACTGGGATCCAAAAAAATATGGTGGTTTTGATAGTCCAACGGTAGCTTATTCAGTCCTAGTGGTTGCTAAGGTGGAAAAAGGGAAATCGAAGAAGTTAAAATCCGTTAAAGAGTTACTAGGGATCACAATTATGGAAAGAAGTTCCTTTGAAAAAAATCCGATTGACTTTTTAGAAGCTAAAGGATATAAGGAAGTTAAAAAAGACTTAATCATTAAACTACCTAAATATAGTCTTTTTGAGTTAGAAAACGGTCGTAAACGGATGCTGGCTAGTGCCGGAGAATTACAAAAAGGAAATGAGCTGGCTCTGCCAAGCAAATATGTGAATTTTTTATATTTAGCTAGTCATTATGAAAAGTTGAAGGGTAGTCCAGAAGATAACGAACAAAAACAATTGTTTGTGGAGCAGCATAAGCATTATTTAGATGAGATTATTGAGCAAATCAGTGAATTTTCTAAGCGTGTTATTTTAGCAGATGCCAATTTAGATAAAGTTCTTAGTGCATATAACAAACATAGAGACAAACCAATACGTGAACAAGCAGAAAATATTATTCATTTATTTACGTTGACGAATCTTGGAGCTCCCGCTGCTTTTAAATATTTTGATACAACAATTGATCGTAAACGATATACGTCTACAAAAGAAGTTTTAGATGCCACTCTTATCCATCAATCCATCACTGGTCTTTATGAAACACGCATTGATTTGAGTCAGCTAGGAGGTGACTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_K180000",
        "type": "gene",
        "description": "Taq DNA Polymerase. Thermostable DNA polymerase for PCR.",
        "sequence": "ATGCGCCTGCTGCGACTGGAGGCCCTGAAGCGCGAAGGCGTGAAGGTGCTGGAATTTCTGGACAAGAACATGAACGCGCACACCGACGCGGTGTTCGAAGGCAAGGAAGCGGAAATCGAACGCAACGCGGAACTGCGCGACGCGCGCGAACGCGCGGAAGAAGTGGCGGCGCTGGGCGTGAAAAACATCATCCGCGAAAAGTGGGAAGCGGCGCCGGAAGCGAACAACGACAAAACCGCGATCTTCGACGACTTTCTGGCGGTGTTTAAAAAAGAAATGCTGAAACTGACCCCGGAAGGCCTGGACATCGAAAAAATCATGAAAGTGTTTAACACCTTCCTGGACAACATGATCGCGAAAAACCTGGGCGTGCTGTTCTTCGATGAAGTGCACAAGATCTTCGAACTGAACGAAACCAAAAACCTGTTTGACGCGATCATCTGCGGCGACTGCCTGGGCATCGACATGTGCCACTTTAACGACAAAACCGAACTGTTCTTCAAGATCATCCCGTGCAACATCGCGCCGAAAGGCGAAGAAATGCTGAAAAAGTACGGCTTCAACAAGGGCGACCTGGTGGTGGCGATCCCGCTGGAAGGCCTGCGCAAGATCTTCCCGAAAAACTTCGACGGCATCATCTTCGACAAGTGCATGAACAAGGAAGGCGACAAGATCGCGCTGGTGATGAAAACCGCGGTGAACGCGCGCATGGACGAACTGGTGAAAGTGAAAGGCGAAGAAACCGAAATCCTGCTGCACGTGCCGGACTTCTACGCGTTCTTCGGCAACGCGATCGCGGAAGCGCTGGGCCCGGAAACCGTGGGCGACATCGTGGTGAAAGCGCTGAAAGAAGCGGGCGTGCCGCTGGCGGTGGACTTCGCGATCGCGACCCCGGAAATCCTGGACAAAAACTTCGGCCTGAAGAACCTGCGCGAAATGTTCATCGACGAAGACATCAAAACCGCGAACGAAGTGGTGAAAGTGATCGACGAAATCATCAAGAAACTGGGCGCGCCGTGCATCGAAATCGTGAAAAACAAGATCACCTACGTGACCGGCATCCTGCGCAACGCGGTGATCGCGCGCGCGCTGGCGGAAGGCGAAGCGAAAGAACTGCTGGCGCGCTGCGACGTGGTGCTGGTGGTGGACTGCAAAACCGGCGACATCCTGATCATCACCGGCCCGAAGGGCGCGGGCAAAACCACCCTGTTCGCGCAGCTGGTGGCGATGCTGAACAAGAAAGGCGTGCTGGCGCTGGTGATCGACGGCCCGAAGGGCGTGTTTGACAAGTGCATCGCGCTGGCGGAAAAGGAAGCGCACATCGTGCGCTTCCTGCCGTTCGCGAACGTGGAAGGCCTGCGCGACTTTCTGCAGGCGGTGGGCTTCACCCCGGAAGTGGTGCTGCTGGACGGCGACATCTTCCGCGAAGCGATCGGCCGCATCCTGGAAAAAGGCAAGATCAAAGTGGTGCTGGAAGTGGCGAAAGGCAAGATCCTGGCGGCGCTGAACGCGGACAAGGAAGGCCTGGCGGCGGCGAAACGCATCATCGAACTGCTGCAAGAACTGCCGAACATCCGCGTGGTGCTGGAACGCGTGGCGCGCCTGGAAATCGAAGGCCTGCGCGTGCGCATCGTGAACATGCCGGAAGTGACCAAAAAAGCGCTGAACGCGCTGGGCCTGCCGATCGAAGCGCGCCTGCGCGAAGCGGGCATCGAAATCCGCAAAAACCTGGAAAACCCGATCATCGAAGGCATCCCGGTGTTCGCGAAAGCGATCGTGCAACGCCTGGCGGCGCGCGGCGTGAAAGCGATCGTGGTGACCGGCCACGACGCGCGCAACCGCATGGTGGAACTGCTGGCGCTGGAAGAAGGCAAAATCCGCCTGGCGGGCGACCCGGCGCTGGAAGCGCTGCGCGACGCGCTGGGCCTGGCGTTCAACGTGCAAGTGAAAGGCCTGGTGGAAGGCCTGGGCCTGGCGATCGAAGCGCTGGGCGTGCCGCCGTTCCTGCACGGCTTCAACCGCGAAGTGGTGGCGATCGGCGCGGTGAACGGCCTGGAACTGCACAAGGCGATGTGA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # Selection markers
    {
        "name": "BBa_P1003",
        "type": "gene",
        "description": "Kanamycin resistance gene. Selection marker for E. coli.",
        "sequence": "ATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_P1004",
        "type": "gene",
        "description": "Ampicillin resistance gene (bla). Selection marker for E. coli.",
        "sequence": "ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    {
        "name": "BBa_P1002",
        "type": "gene",
        "description": "Chloramphenicol resistance gene. Selection marker for E. coli.",
        "sequence": "ATGGAGAAAAAAATCACTGGATATACCACCGTTGATATATCCCAATGGCATCGTAAAGAACATTTTGAGGCATTTCAGTCAGTTGCTCAATGTACCTATAACCAGACCGTTCAGCTGGATATTACGGCCTTTTTAAAGACCGTAAAGAAAAATAAGCACAAGTTTTATCCGGCCTTTATTCACATTCTTGCCCGCCTGATGAATGCTCATCCGGAATTCCGTATGGCAATGAAAGACGGTGAGCTGGTGATATGGGATAGTGTTCACCCTTGTTACACCGTTTTCCATGAGCAAACTGAAACGTTTTCATCGCTCTGGAGTGAATACCACGACGATTTCCGGCAGTTTCTACACATATATTCGCAAGATGTGGCGTGTTACGGTGAAAACCTGGCCTATTTCCCTAAAGGGTTTATTGAGAATATGTTTTTCGTCTCAGCCAATCCCTGGGTGAGTTTCACCAGTTTTGATTTAAACGTGGCCAATATGGACAACTTCTTCGCCCCCGTTTTCACCATGGGCAAATATTATACGCAAGGCGACAAGGTGCTGATGCCGCTGGCGATTCAGGTTCATCATGCCGTTTGTGATGGCTTCCATGTCGGCAGAATGCTTAATGAATTACAACAGTACTGCGATGAGTGGCAGGGCGGGGCGTAA",
        "organism": "ecoli",
        "source": "iGEM",
    },
    # Yeast parts
    {
        "name": "BBa_K801010",
        "type": "promoter",
        "description": "TEF1 promoter for S. cerevisiae. Strong constitutive promoter.",
        "sequence": "ATAGCTTCAAAATGTTTCTACTCCTTTTTTACTCTTCCAGATTTTCTCGGACTCCGCGCATCGCCGTACCACTTCAAAACACCCAAGCACAGCATACTAAATTTCCCCTCTTTCTTCCTCTAGGGTGTCGTTAATTACCCGTACTAAAGGTTTGGAAAAGAAAAAAGAGACCGCCTCGTTTCTTTTTCTTCGTCGAAAAAGGCAATAAAAATTTTTATCACGTTTCTTTTTCTTGAAAATTTTTTTTTTTGATTTTTTTCTCTTTCGATGACCTCCCATTGATATTTAAGTTAATAAACGGTCTTCAATTTCTCAAGTTTCAGTTTCATTTTTCTTGTTCTATTACAACTTTTTTTACTTCTTGCTCATTAGAAAGAAAGCATAGCAATCTAATCTAAGTTTTAATTACAAA",
        "organism": "yeast",
        "source": "iGEM",
    },
    {
        "name": "BBa_K105030",
        "type": "promoter",
        "description": "ADH1 promoter for S. cerevisiae. Strong constitutive promoter.",
        "sequence": "CGGATTTCCTTTATGACTTGATTATTTTTAAATGTTTTTGTTTATAACTTTTGCTCTATGCATCGCATCATTCATGCAAGGATGAGTTTTAGGAATGAAGTCGAAATGTTCGTTCATAGGCCATGTAAAATGATAAAATTGTTTACTAGAGATTTAGGCTTTTTCAATTTTGATAATCAATAAAAAGTTATTTTCTCTCATTTTAGTTTAAATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAGTTTTATATAGATGGAGTTTTTTTTTTCATAAGTACTCTAAAATGCACGTCAAATAAAGATAAGAATGAGTCAATCGAAGGTTTGTTCTGAGGGTTTTTTTTTTTTTTTTTTTTTTTTGGGATCGATCTTATTTGAATTTTCTTTAATTTAGATAATTTTAGTTTTTAAGTTTTAAAGAGAGTTTATTTGTTTTTTTTTTAATGTTGAATTTAATTGTATATATAATTTATTGCTCAATTGAATTTGAATGAATTGAATTAATAAATAAATAGATCAATTTTCACGTAAAAATATTAGTTTTTTTATTTGTTTTTTTAGTTTATTTTTTTTTCCTTATTTTTCTTATACAATTTTATAAATATATAAATTTATTGAAAACTCTATCTAATTTATAAGAATATATATTACAAATGGATAAATGTACTTTGAACGAATTTGATCCATCGTAACAATAGTTGATGTAGATGACAGATTGGTATTGTCGGTATAATTTTTTTTTGGTTATAAAAGTGCTATAATCACTCAGAATATCTATTCATGTATGATCAATTGCAAAAAATTTTTTTCGATTTGTGATGAAAAAAATTAGCCAAAAATAAATAAACTTAAATTATTATGTAAGATATATATTGTTGATTAATGAGTCATAATCGGTTGATCTAGAGAAAGAGTTTGTAGAAACGCAAAAAGGCCATCCGTCAGGATGGCCTTCTGCTTAGTTTGATGCCTGGCAGTTCCCTACTCTCGCATGGGGAGACCCCACACTACCATCGGCGCTACGGCGTTTCACTTCTGAGTTCGGCATGGGGTCAGGTGGGACCACCGCGCTACTGCCGCCAGGCAAATTCTGTTTTATCAGACCGCTTCTGCGTTCTGATTTAATCTGTATCAGGCTGAAAATCTTCTCTCATCCGCCAAAACAGCCAAGCTC",
        "organism": "yeast",
        "source": "iGEM",
    },
    {
        "name": "BBa_K392002",
        "type": "rbs",
        "description": "Yeast Kozak sequence. Consensus sequence for translation initiation in S. cerevisiae.",
        "sequence": "AAAAATGTCT",
        "organism": "yeast",
        "source": "iGEM",
    },
    {
        "name": "BBa_K110012",
        "type": "gene",
        "description": "LEU2 gene. Leucine biosynthesis, used as auxotrophic marker in yeast.",
        "sequence": "ATGTCTGCCCCTAAGAAGATCGTCGTTTTGCCAGGTGACCACGTTGGTCAAGAAATCACAGCCGAAGCCATTAAGGTTCTTAAAGCTATTTCTGATGTTCGTTCCAATGTCAAGTTCGATTTCGAAAATCATTTAATTGGTGGTGCTGCTATCGATGCTACAGGTGTTCCACTTCCAGATGAGGCGCTGGAAGCCTCCAAGAAGGCTGATGCCGTTTTGTTAGGTGCTGTGGGTGGTCCTAAATGGGGTACCGGTAGTGTTAGACCTGAACAAGGTTTACTAAAAATCCGTAAAGAACTTCAATTGTACGCCAACTTAAGACCATGTAACTTTGCATCCGACTCTCTTTTAGACTTATCTCCAATCAAGCCACAATTTGCTAAAGGTACTGACTTCGTTGTTGTCAGAGAATTAGTGGGAGGTATTTACTTTGGTAAGAGAAAGGAAGACGATGGTGATGGTGTCGCTTGGGATAGTGAACAATACACCGTTCCAGAAGTGCAAAGAATCACAAGAATGGCCGCTTTCATGGCCCTACAACATGAGCCACCATTGCCTATTTGGTCCTTGGATAAAGCTAATGTTTTGGCCTCTTCAAGATTATGGAGAAAAACTGTGGAGGAAACCATCAAGAACGAATTCCCTACATTGAAGGTTCAACATCAATTGATTGATTCTGCCGCCATGATCCTAGTTAAGAACCCAACCCACCTAAATGGTATTATAATCACCAGCAACATGTTTGGTGATATCATCTCCGATGAAGCCTCCGTTATCCCAGGTTCCTTGGGTTTGTTGCCATCTGCGTCCTTGGCCTCTTTGCCAGACAAGAACACCGCATTTGGTTTGTACGAACCATGCCACGGTTCTGCTCCAGATTTGCCAAAGAATAAGGTCAACCCTATCGCCACTATCTTGTCTGCTGCAATGATGTTGAAATTGTCATTGAACTTGCCTGAAGAAGGTAAGGCCATTGAAGATGCAGTTAAAAAGGTTTTGGATGCAGGTATCAGAACTGGTGATTTAGGTGGTTCCAACAGTACCACCGAAGTCGGTGATGCTGTCGCCGAAGAAGTTAAGAAAATCCTTGCTTAA",
        "organism": "yeast",
        "source": "iGEM",
    },
]


def add_parts():
    """Add additional parts to the database."""
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    added = 0
    skipped = 0

    try:
        for part_data in ADDITIONAL_PARTS:
            # Check if part already exists
            existing = db.query(Part).filter(Part.name == part_data["name"]).first()
            if existing:
                skipped += 1
                continue

            part = Part(**part_data)
            db.add(part)
            added += 1

        db.commit()
        print(f"Added {added} new parts ({skipped} already existed)")

        # Print summary by type
        for ptype in ["promoter", "rbs", "terminator", "gene"]:
            count = sum(1 for p in ADDITIONAL_PARTS if p["type"] == ptype)
            print(f"  - {count} {ptype}s")

    finally:
        db.close()


if __name__ == "__main__":
    add_parts()
